/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/

var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
    alert($(this).text());
    var city = $(this).text();
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;
           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var Temp = Math.round((weatherInfo.item.condition.temp-32)*(5/9));
           $('.temperature').text (Temp);
       var Time = (weatherInfo.item.forecast[0].date)
           $('.date').text(Time);
       var Weather = (weatherInfo.item.condition.text);
           $('.condition p').text (Weather);
           $('tr th:nth-child(1)').text(weatherInfo.item.forecast[1].date);     
           $('tr th:nth-child(2)').text(weatherInfo.item.forecast[2].date);  
           $('tr th:nth-child(3)').text(weatherInfo.item.forecast[3].date);  
       var Temperature1 = Math.round((weatherInfo.item.forecast[1].low - 32)*(5/9)) + '-' +
                          Math.round((weatherInfo.item.forecast[1].high - 32)*(5/9))
           $('tr td:nth-child(1) p').text(Temperature1);               
       var Temperature2 = Math.round((weatherInfo.item.forecast[2].low - 32)*(5/9)) + '-' +
                          Math.round((weatherInfo.item.forecast[2].high - 32)*(5/9))
           $('tr td:nth-child(2) p').text(Temperature1);
       var Temperature3 = Math.round((weatherInfo.item.forecast[3].low - 32)*(5/9)) + '-' +
                          Math.round((weatherInfo.item.forecast[3].high - 32)*(5/9))
           $('tr td:nth-child(3) p').text(Temperature1);     

       var Icon = weatherInfo.item.forecast[0].text;
           var Icon1 = weatherInfo.item.forecast[1].text;
           var Icon2 = weatherInfo.item.forecast[2].text;
           var Icon3 = weatherInfo.item.forecast[3].text;

       skycons.set("today",Icon);
       skycons.set("day1",Icon1);
       skycons.set("day2",Icon2);
       skycons.set("day3",Icon3);

       skycons.play();
       
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});



